# -*- coding: utf-8 -*-
"""appP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dykw4rfiD-qyn9PtMV86jsbskdD7f7A4
"""

import streamlit as st
import joblib

# Load model and vectorizer
model = joblib.load("fake_news_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# UI/UX Layout
st.set_page_config(page_title="🧠 Fake News Detector", layout="wide")

st.markdown("<h1 style='text-align: center;'>🧠 Fake News or Not?</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>Detect AI-generated or fake news articles instantly.</p>", unsafe_allow_html=True)

text_input = st.text_area("Enter a news article or headline", height=200)

if st.button("Analyze"):
    if text_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        input_vector = vectorizer.transform([text_input])
        prediction = model.predict(input_vector)[0]

        if prediction == 1:
            st.success("✅ This news looks **REAL**.")
        else:
            st.error("🚫 This news seems **FAKE** or AI-generated.")